#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2019-07-17 14:18
# @Author  : Mermaid  
# @File    : practice15.py
# 学生成绩管理系统
#     1.根据姓名查看学生所有成绩
#     2.查看所有人的某学科成绩
#     3.查看总平均分
#     4.查看某人的某学科成绩
#     5.根据姓名删除学生信息
#
# 增强版要求(选做)
#     1.首先编写json格式的数据文件  内容为学生
#     2.将json数据解析后转换为学生对象在进行增删改查
class student:
    school = 'deepshare'

    def __init__(self, name, NianJi, ShuXue, YuWen):
        self.name = name
        self.NianJi = NianJi
        self.ShuXue = ShuXue
        self.YuWen = YuWen

    def get_name(self):
        return self.name

    def get_NianJi(self):
        return self.NianJi

    def get_ShuXue(self):
        return self.ShuXue

    def get_YuWen(self):
        return self.YuWen

    def print_all_score(self):
        print('%s的数学成绩：%3d,语文成绩：%3d' % (self.name,
                                        self.ShuXue,
                                        self.YuWen))

    def print_one_score(self, subject):
        if subject == 'ShuXue':
            print('%s的数学成绩：%3d' % (self.name,
                                   self.ShuXue))
        elif subject == 'YuWen':
            print('%s的语文成绩：%3d' % (self.name,
                                   self.YuWen))


stu1 = student('张三', 1, 100, 90)
stu2 = student('李四', 2, 90, 100)
stu = {stu1, stu2}
print(type(stu))

# 查看所有成绩
for astu in stu:
    astu.print_all_score()
print('=' * 20)

# 查看所有人的某学科成绩
for astu in stu:
    astu.print_one_score('ShuXue')
print('=' * 20)
# .查看总平均分
total = 0
num = 0
for astu in stu:
    total += astu.get_ShuXue()
    total += astu.get_YuWen()
    num += 2
print('总平均分', total / num)
print('=' * 20)
# 4.查看某人的某学科成绩
name = '张三'
xueke = 'ShuXue'
for astu in stu:
    if name == astu.get_name():
        astu.print_one_score(xueke)
